# Uncomment this line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

def shared_pods
  # Toast Swift
  pod 'Toast-Swift', '~> 5.0.1'
  
  # SD Web Image
  pod 'SDWebImage', '~> 5.0'

end

target 'ImSplash' do
    shared_pods
end
