# Uncomment this line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

def shared_pods  
  # Alamofire
  pod 'Alamofire', '5.0'

  # SV Progress HUD
  pod 'SVProgressHUD', '2.2.5'
  
  # Swifty JSON
  pod 'SwiftyJSON', '~> 4.0'
  
  # SD Web Image
  pod 'SDWebImage', '~> 5.0'

end

target 'ImSplash' do
    shared_pods
end
